#!/bin/sh

# PROVIDE: unitedscifi
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# unitedscifi_enable (bool): Set to NO by default. Set this variable to YES if you want to enable unitedscifi service.
# unitedscifi_config (path): Set to /usr/local/etc/unitedscifi.conf by default.
# unitedscifi_user:  The user account unitedscifi daemon runs as. It uses 'root' user by default.
# unitedscifi_group: The group account unitedscifi daemon runs as. It uses 'wheel' group by default.
# unitedscifi_datadir (str): Default to "/var/db/unitedscifi". Base data directory.

. /etc/rc.subr

name=unitedscifi
rcvar=unitedscifi_enable

: ${unitedscifi_enable:=NO}
: ${unitedscifi_config=/usr/local/etc/unitedscifi.conf}
: ${unitedscifi_datadir=/var/db/unitedscifi}
: ${unitedscifi_user="root"}
: ${unitedscifi_group="wheel"}

required_files=${unitedscifi_config}
command=/usr/local/bin/unitedscifid
unitedscifi_chdir=${unitedscifi_datadir}
pidfile="${unitedscifi_datadir}/unitedscifid.pid"
stop_cmd=unitedscifi_stop
command_args="-conf=${unitedscifi_config} -datadir=${unitedscifi_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

unitedscifi_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${unitedscifi_datadir}
	[ $? -eq 0 ] && chown -R ${unitedscifi_user}:${unitedscifi_group} ${unitedscifi_datadir}
}

unitedscifi_prestart()
{
	if [ ! -d "${unitedscifi_datadir}/." ]; then
		unitedscifi_create_datadir || return 1
	fi
}

unitedscifi_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

unitedscifi_stop()
{
    unitedscifi_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${unitedscifi_config} -datadir=${unitedscifi_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
